import { useEffect, useState } from 'react'
import InfoTip from './UI/InfoTip.jsx'

export default function AlertsPanel(){
  const [items, setItems] = useState(() => {
    const init = Array.isArray(window.__alerts) ? window.__alerts : []
    return init
  })

  useEffect(()=>{
    window.__alerts = items
    document.dispatchEvent(new Event('alerts-changed'))
  }, [items])

  useEffect(()=>{
    const onPipeline = (e) => {
      const { type = 'failure', step } = e.detail || {}
      pushAlert({ source: 'Pipeline', type, message: `${type.toUpperCase()} at step ${step}` })
    }
    const onMonitor = (e) => {
      const d = e.detail || {}
      const severity = d.severity || (d.type === 'down' ? 'error' : 'warn')
      const message = d.message || (d.type === 'down' ? 'Ping failed' : `High latency: ${Math.round(d.latencyMs||0)} ms`)
      pushAlert({ source: 'Monitor', type: severity, message })
    }
    const onClear = () => setItems([])
    document.addEventListener('pipeline-alert', onPipeline)
    document.addEventListener('monitor-alert', onMonitor)
    document.addEventListener('alerts-clear', onClear)
    return ()=>{
      document.removeEventListener('pipeline-alert', onPipeline)
      document.removeEventListener('monitor-alert', onMonitor)
      document.removeEventListener('alerts-clear', onClear)
    }
  }, [])

  const pushAlert = (a) => {
    const item = { id: Date.now(), time: new Date(), ...a, acked: false, resolved: false }
    setItems(prev => [item, ...prev].slice(0,20))
  }

  const ack = (id) => setItems(prev => prev.map(a => a.id===id ? { ...a, acked: true } : a))
  const resolve = (id) => setItems(prev => prev.map(a => a.id===id ? { ...a, resolved: true } : a))
  const clearResolved = () => setItems(prev => prev.filter(a => !a.resolved))

  return (
    <div className="border rounded-lg p-3 bg-white">
      <h3 className="font-semibold text-brand mb-2 flex items-center gap-2">Alerts <InfoTip text="Synthetic alerts generated by pipeline failures or monitor latency/ping issues." /></h3>
      {items.length === 0 ? (
        <p className="text-sm text-slate-600">No alerts.</p>
      ) : (
        <ul className="text-sm space-y-2">
          {items.map(a => (
            <li key={a.id} className="border rounded p-2 bg-slate-50 flex items-center justify-between">
              <div>
                <div className="font-semibold text-brand">{a.source} · {a.type}</div>
                <div className="text-xs text-slate-600">{a.message}</div>
                <div className="text-xs text-slate-500">{a.time.toLocaleString()}</div>
              </div>
              <div className="flex gap-2">
                <button className="btn" onClick={()=>ack(a.id)} disabled={a.acked}>Ack</button>
                <button className="btn" onClick={()=>resolve(a.id)} disabled={a.resolved}>Resolve</button>
              </div>
            </li>
          ))}
        </ul>
      )}
      <div className="mt-2">
        <button className="btn" onClick={clearResolved}>Clear Resolved</button>
      </div>
    </div>
  )
}
